config/routes.rb
Itsmyparty::Application.routes.draw do


  resources :parties do
    member do
      post 'rsvp'
    end
    resources :invites do
      resources :comments, only: :create
      resources :pictures, only: :create
    end
  end


  root :to => "parties#index"

end

app/models/invite.rb
class Invite < ActiveRecord::Base

  scope :yes, -> {where(status: 'yes')}
  scope :no, -> {where(status: 'no')}
  scope :maybe, -> {where(status: 'maybe')}
  scope :no_answer, -> {where(status: 'no_answer')}

  belongs_to :party
  has_many :comments
  has_many :pictures

  before_validation :create_key_if_necessary

  def invitation_text
    self.custom_invitation.blank? ? "Hello #{self.name}! \n\n #{self.party.invitation_text}" : self.custom_invitation
  end


  def is_invite_key?(key)
    key == invite_key
  end

  private

  def create_key_if_necessary
    self.invite_key ||= SecureRandom.base58(24)
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  load_and_authorize_resource :party
  load_and_authorize_resource :invite, :through => :party
  # GET /parties/invites
  # GET /parties/invites.json
  def index

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @invites }
    end
  end

  # GET /parties/invites/1
  # GET /parties/invites/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @invite }
    end
  end

  # GET /parties/invites/new
  # GET /parties/invites/new.json
  def new

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @invite }
    end
  end

  # GET /parties/invites/1/edit
  def edit
  end

  # POST /parties/invites
  # POST /parties/invites.json
  def create

    @invite.party = Party.find(params[:party_id])
    @invite.status = "no_answer"

    respond_to do |format|
      if @invite.save

        unless @invite.email.blank?
          PartyMailer.invited(@invite).deliver
          format.html { redirect_back fallback_location: root_path }
          format.json  { render :json => @invite, :status => :created, :location => @invite }
        else
          format.html { redirect_to party_invite_path(@invite.party, @invite) }
          format.json  { render :json => @invite, :status => :created, :location => @invite }
        end
      else
        format.html { render :action => "new" }
        format.json  { render :json => @invite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /parties/invites/1
  # PUT /parties/invites/1.json
  def update

    respond_to do |format|
      if @invite.update_attributes(invite_params)
        logger.info @invite.inspect
        format.html { redirect_back fallback_location: root_path, notice: 'Invite was successfully updated.' }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @invite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/invites/1
  # DELETE /parties/invites/1.json
  def destroy
    @invite.destroy

    respond_to do |format|
      format.html { redirect_to(parties_invites_url) }
      format.json  { head :ok }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  private
  def invite_params
    params[:invite].permit!
  end

end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/_banner.html.erb
<div class="block banner-block">
  <% if @invite.party.banner.attached? %>
    <%= image_tag @invite.party.banner, class: 'pure-img banner-img' %>
  <% end %>
</div>
<div class="block pure-g">
  <div class="pure-u-1-4 pure-u-md-1-6">
    <div class="month-block">
      <%=h @invite.party.start.strftime("%B")%>
    </div>
    <div class="day-of-month-block">
      <%=h @invite.party.start.strftime("%-d")%>
    </div>
  </div>
  <div class="pure-u-3-4 pure-u-md-5-6">
    <h1 class="invite-header"><%=h @invite.party.topic %></h1>
    <div>
      <a href="mailto:<%=@invite.party.creator_mail%>"><%=@invite.party.creator_name%></a>
      invited you to this event.
    </div>
  </div>
</div>

app/views/invites/_comments.html.erb
<div class="block" id="comments">
  <h2>
    Comments
  </h2>
  <%= form_for([@party, @invite, Comment.new(invite: @invite)], html: {class: 'pure-form'}) do |f| %>
    <p>
      <%= f.text_area :text, rows: 1, class: 'pure-u-1' %>
      <%= f.submit 'Post' , class: 'pure-u-1'%>
    </p>
  <% end %>
</div>
<% @party.comments.order(created_at: :desc).each do | comment | %>
  <div class="block">
    <div class="comment-data">
      <div class="comment-author">
        <%= comment.invite.name %>
      </div>
      <div class="comment-timestamp">
        <%= time_ago_in_words comment.created_at %> ago
      </div>
    </div>
    <div class="comment-text">
      <%= markdown comment.text %>
    </div>
  </div>
<% end %>

app/views/invites/_details.html.erb
<div class="block pure-g">
  <div class="pure-u-1-12">
    <%= fa_icon 'clock-o' %>
  </div>
  <div class="pure-u-2-3">
    <%=h @invite.party.start.strftime('%H:%M') %>
  </div>
  <div class="pure-u-1-4">
    <a href="#comments">
      <%= fa_icon 'comments' %>
      Comments
    </a>
  </div>
  <div class="pure-u-1-12">
    <%= fa_icon 'map-marker' %>
  </div>
  <div class="pure-u-2-3">
    <%=h @invite.party.location %>
  </div>
  <div class="pure-u-1-4">
    <a href="#comments">
      <%= fa_icon 'image' %>
      Gallery
    </a>
  </div>
</div>

app/views/invites/_edit_and_invite.html.erb
<div class="block pure-g">
  <div class="pure-u-1-2">
    <%if @party.may_edit?(params[:key])%>
      <%= link_to 'Edit', edit_party_path(@party) %>
    <%end%>
  </div>
  <% if @party.may_invite?(params[:key]) %>
    <div class="pure-u-1-2">
      <a data-toggle="collapse" href="#invitation-form">
        Invite people
      </a>
    </div>
    <div id="invitation-form" class="collapse pure-u-1">
      <h2>Create Invitation</h2>
      <%= form_for([@party, Invite.new], html: {class: 'pure-form'}) do |f| %>
        <p>
          <%= f.label :name%><br />
          <%= f.text_field :name %>
        </p>

        <p>
          <%= f.label :email %><br />
          <%= f.email_field :email %>
        </p>
        <p>
          <%= f.label :custom_invitation %><br />
          <%= f.text_area :custom_invitation, :rows => 4%>
        </p>
        <p>
          <%= f.label :role %><br />
          <%= f.select(:role, options_for_select(['guest', 'admin'])) %>
        </p>
        <p>
          <%= f.submit 'Create' %>
        </p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/invites/_gallery.html.erb
<div class="block" id="gallery">
    <h2>
      Gallery
    </h2>
  <%= form_for([@party, @invite, Picture.new(invite: @invite)], html: {class: 'pure-form', id: 'picture-form'}) do |f| %>
    <p>
      <%= f.file_field :picture %>
      <%= f.submit 'Post' %>
    </p>
  <% end %>
</div>
<% @party.pictures.order(created_at: :desc).each do | picture | %>
  <div class="block">
    <div class="comment-data">
      <div class="comment-author">
        <%= picture.invite.name %>
      </div>
      <div class="comment-timestamp">
        <%= time_ago_in_words picture.created_at %> ago
      </div>
    </div>
    <%= image_tag picture.picture, class: 'pure-img gallery-img' %>
  </div>
<% end %>

app/views/invites/_partygoers.html.erb
<div class="block pure-g">
  <% if @invite.party.invites.yes.count > 0 %>
    <div class="pure-u-1-12">
      <%= fa_icon 'check-circle' %>
    </div>
    <div class="pure-u-5-12">
      <% @invite.party.invites.yes.each do |invite| %>
        <%=h  invite.name %>
        <br>
      <% end %>
    </div>
  <% end %>
  <% if @invite.party.invites.maybe.count > 0 %>
    <div class="pure-u-1-12">
      <%= fa_icon 'star' %>
    </div>
    <div class="pure-u-5-12">
      <% @invite.party.invites.maybe.each do |invite| %>
        <%=h  invite.name %>
        <br>
      <% end %>
    </div>
  <% end %>
</div>

app/views/invites/_shareable.html.erb
<div class="block">
  <h2>Shareable Text</h2>
  <%= markdown @invite.invitation_text %>

  Please be nice and tell
  <a href="mailto:<%=@invite.party.creator_mail%>"><%=@invite.party.creator_name%></a>
  if you're coming at
  <a href="<%=party_invite_url(@invite.party, @invite, :key => @invite.invite_key)%>"
  ><%=party_invite_url(@invite.party, @invite, :key => @invite.invite_key)%></a>.

  Don't miss the fun & party hard!
</div>

app/views/invites/_status_forms.html.erb
<div class="block pure-g">
  <div class="pure-u-1-4 pure-u-md-1-6 status-block">
    <% if @invite.status == 'yes' %>
      <%= fa_icon 'check-circle' %>
    <% end %>
    <% if @invite.status == 'maybe' %>
      <%= fa_icon 'star' %>
    <% end %>
    <% if @invite.status == 'no' %>
      <%= fa_icon 'times-circle' %>
    <% end %>
    <% if @invite.status == 'no_answer' %>
      <%= fa_icon 'question-circle' %>
    <% end %>
  </div>
  <div class="pure-u-3-4 pure-u-md-5-6 status-change-block">
    <% if @invite.status != 'yes' %>
      <%= form_for([@invite.party, @invite]) do |f|%>
        <%=  f.hidden_field :status, :value => "yes" %>
        <button type="submit">
          <%= fa_icon 'check-circle' %> <%= "Yes!"%>
        </button>
      <%  end %>
    <% end %>
    <% if @invite.status != 'maybe' %>
      <%= form_for([@invite.party, @invite]) do |f|%>
        <%=  f.hidden_field :status, :value => 'maybe' %>
        <button type="submit">
          <%= fa_icon 'star' %> <%= "Maybe"%>
        </button>
      <%  end %>
    <% end %>
    <% if @invite.status != 'no' %>
      <%= form_for([@invite.party, @invite]) do |f|%>
        <%=  f.hidden_field :status, :value => 'no' %>
        <button type="submit">
          <%= fa_icon 'times-circle' %> <%= "No"%>
        </button>
      <% end %>
    <% end %>
  </div>
</div>

app/views/invites/show.html.erb
<% title "Invitation for #{@invite.name} to #{@invite.party.topic}" %>



<div class="block">
  <%= markdown @invite.invitation_text %>
</div>

<%= render 'banner' %>

<% if @invite.is_invite_key?(params[:key]) %>
  <%= render 'status_forms' %>
<% end %>

<%= render 'details' %>

<%= render 'partygoers' %>

<div class="block">
  <%=h markdown @invite.party.description %>
</div>

<% unless @invite.is_invite_key?(params[:key]) %>
  <%= render 'shareable' %>
<% end %>


<% if @invite.is_invite_key?(params[:key]) %>
  <%= render 'edit_and_invite' %>
  <%= render 'comments' %>
  <%= render 'gallery' %>
<% end %>