config/routes.rb
Itsmyparty::Application.routes.draw do


  resources :parties do
    member do
      post 'rsvp'
    end
    resources :invites do
      resources :comments, only: :create
      resources :pictures, only: :create
    end
  end


  root :to => "parties#index"

end

app/models/party.rb
class Party < ActiveRecord::Base

  has_many :invites
  has_many :comments, through: :invites
  has_many :pictures, through: :invites
  has_one_attached :banner

  def is_admin_key?(key)
    invites.any? { |invite| invite.invite_key == key && invite.role == "admin" }
  end

  def may_invite?(key)
    is_admin_key?(key)
  end

  def may_edit?(key)
    is_admin_key?(key)
  end

  def may_see?(key)
    invites.any?{ |invite| invite.is_invite_key?(key) }
  end

  def invitation_text
    self.default_invitation.blank? ? "You have been invited to #{self.topic}!" : self.default_invitation
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  load_and_authorize_resource

  # GET /parties
  # GET /parties.json
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
    respond_to do |format|
      if params[:key]
        redirect_to party_invite_path(@party, Invite.find_by(invite_key: params[:key], party: @party))
      else
        format.html { render action: 'show' }
      end
    end
  end

  # GET /parties/new
  # GET /parties/new.json
  def new

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @party }
    end
  end

  # GET /parties/1/edit
  def edit
  end

  # POST /parties
  # POST /parties.json
  def create
    respond_to do |format|
      if @party.save
        invite = Invite.new
        invite.email = @party.creator_mail
        invite.status = "yes"
        invite.role = "admin"
        invite.name = @party.creator_name
        invite.party = @party
        invite.inviter = @party.creator_mail
        invite.save

        @party.reload

        PartyMailer.created(@party).deliver  #party_created @party

        format.html { render action: 'created' }
        format.json  { render :status => :created }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @party.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /parties/1
  # PUT /parties/1.json
  def update
    respond_to do |format|
      if @party.update_attributes(party_params)
        flash[:notice] = 'Party was successfully updated.'
        format.html { redirect_to party_invite_path(@party, invite, key: invite.invite_key) }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @party.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party = Party.find(params[:id])
    @party.destroy

    respond_to do |format|
      format.html { redirect_to(parties_url) }
      format.json  { head :ok }
    end
  end

  def rsvp
    @invite = Invite.create(invite_params)
    @invite.party = @party
    @invite.status = 'yes'
    @invite.role = 'guest'
    @invite.custom_invitation = "Hello #{@invite.name}! \n\n Thanks for joining #{@party.topic}!"
    @invite.save!
    PartyMailer.invited(@invite).deliver
    redirect_to party_invite_path(@party, @invite, key: @invite.invite_key)
  end

  private

  def invite_params
    params[:invite].permit([:name, :email])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def party_params
    params[:party].permit([:banner, :topic, :creator_name, :creator_mail, :location, :start, :end, :description, :default_invitation])
  end

end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_form.html.erb
<%= form_for(@party, html: {class: 'pure-form'}) do |f| %>
  <% if @party.errors.any? %>
    <div id="error_explanation" class="block">
      <h2><%= pluralize(@party.errors.count, "error") %> prohibited this parties_invite from being saved:</h2>

      <ul>
      <% @party.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="block">
    <p>
      <%= f.label :creator_name, "Your name"%><br />
      <%= f.text_field :creator_name %>
    </p>

    <p>
      <%= f.label :creator_mail, "Your e-mail address"%><br />
      <%= f.text_field :creator_mail %>
    </p>

    <p>
      <%= f.label :location %><br />
      <%= f.text_field :location %>
    </p>
    <p>
      <%= f.label :start %><br />
      <%= f.datetime_select :start %>
    </p>
    <p>
      <%= f.label :topic %><br />
      <%= f.text_field :topic %>
    </p>
    <p>
      <%= f.label :banner, "Party Banner"%><br />
      <%= f.file_field :banner %>
    </p>
    <p>
      <%= f.label :description %><br />
      <%= f.text_area :description, :rows => 20, :class => 'pure-u-1' %>
    </p>
    <p>
      <%= f.label :default_invitation %><br />
      <%= f.text_area :default_invitation, :rows => 10, :class => 'pure-u-1' %>
    </p>
    <p>
      <%= f.submit 'Save' %>
    </p>
  </div>
<% end %>

app/views/parties/create.html.erb
<h2>Hello <%=@party.creator_mail %>!</h2>

<p>Thank you for using itsmyparty!</p>

<p>
Your party <%=@party.topic %> was created and you can start inviting 
people <%=link_to "here", party_path(@party, :key => @party.invites.select { |invite| invite.email == @party.creator_mail }[0].invite_key)%>
</p>

<p>
If you want to throw a real big party and invite more than 15 people without
being hassled by Captchas, please create an account with itsmyparty (We have 
to do this to avoid being used by those pesky spammers)
</p>

<p>
Have fun & party hard!
</p>

app/views/parties/created.html.erb
<div class="block">
  <p>
    Your party <%=@party.topic %> was created.
  </p>
  <p>
    An email was sent to <%= @party.creator_mail %>. Click on the link in the mail to start inviting people!
  </p>
  <p>
    <%= link_to 'Back', root_path %>
  </p>
</div>

app/views/parties/edit.html.erb
<div class="block">
  <h1>Editing party</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<div class="block">
  <h1>It's my party!</h1>
</div>
<div class="block">
  <%= link_to 'Create your party!', new_party_path, class: 'call-to-action' %>
</div>
<div class="block">
  <h2>What is it?</h2>
  <p>
    <strong>It's my party</strong> is a place where you can invite your friends
    to parties and where they can easily RSVP. People you invite can also write
    comments.<br>
    Think of it as a replacement for Facebook events.
  </p>
</div>
<div class="block">
  <h2>How does it look?</h2>
  <p>
    I modeled the look after the thing it should replace to present people with
    a familiar user experience.
  </p>
  <p>
    <img class="screenshot" src="/img/itsmyparty-screenshot.png">
  </p>
</div>
<div class="block">
  <h2>How do I invite my friends?</h2>
  <p>
    If you add an email address when creating an invitation an email is sent to
    that person containing a link to the party.<br>
    If not, you are presented with a text you can
  </p>
</div>
<div class="block">
  <h2>Why did you build it?</h2>
  <p>
    I built <strong>It's my party</strong> because more and more people I want
    to invite to parties move off Facebook and because I'm working on replacing
    Facebook for me personally.
  </p>

</div>

app/views/parties/new.html.erb
<div class="block">
  <h1>New party</h1>
</div>
<%= render 'form' %>

app/views/parties/show.html.erb
<div class="block banner-block">
  <% if @party.banner.attached? %>
    <%= image_tag @party.banner, class: 'pure-img banner-img' %>
  <% end %>
</div>
<div class="block pure-g">
  <div class="pure-u-1-4 pure-u-md-1-6">
    <div class="month-block">
      <%=h @party.start.strftime("%B")%>
    </div>
    <div class="day-of-month-block">
      <%=h @party.start.strftime("%-d")%>
    </div>
  </div>
</div>
<div class="block pure-g">
  <div class="pure-u-1-12">
    <%= fa_icon 'clock-o' %>
  </div>
  <div class="pure-u-11-12">
    <%=h @party.start.strftime('%H:%M') %>
  </div>
  <div class="pure-u-1-12">
    <%= fa_icon 'map-marker' %>
  </div>
  <div class="pure-u-11-12">
    <%=h @party.location %>
  </div>
</div>

<div class="block">
  <%=h markdown @party.description %>
</div>

<div class="block pure-g">

  <div id="invitation-form" class="pure-u-1">
    <h2>RSVP</h2>
    <%= form_for([@party, Invite.new], url: rsvp_party_path(@party), html: {class: 'pure-form'}) do |f| %>
      <%= f.hidden_field :role, value: 'guest' %>
      <%= f.hidden_field :status, value: 'yes' %>
      <p>
        <%= f.label :name%><br />
        <%= f.text_field :name %>
      </p>

      <p>
        <%= f.label :email %><br />
        <%= f.email_field :email %>
      </p>
      <p>
        <%= f.submit 'RSVP' %>
      </p>
    <% end %>
  </div>
</div>